---
- name: Provision Raspberry Pi
  hosts: all
  become: true
  roles:
    - raspi_features
    - geerlingguy.docker
  tasks:
    - name: Update raspi-config itself
      become: true
      ansible.builtin.apt:
        name: raspi-config
        update_cache: true
        state: present
        cache_valid_time: 3600
      when: UPDATE | default(false)

    - name: Set Hostname
      ansible.builtin.hostname:
        name: <HOSTNAME>

- name: Create Runner User
  import_playbook: playbooks/user.yml
  vars:
    user: <USER>
    new_password: <PASSWORD>
    user_groups: ["docker"]

- name: Install/Configure Packages
  import_playbook: playbooks/packages.yml

- name: Configure GitHub Actions Runner
  hosts: all
  become: true
  roles:
    - MonolithProjects.github_actions_runner
  vars:
    - runner_user: <USER>
    - runner_dir: home/<USER>
    - github_account: <GITHUB_USER>
    - github_repo: <GITHUB_REPO>
    - access_token: <GITHUB_TOKEN>
